import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionContext } from "@/api/session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: JSX.Element }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionContext>{children}</SessionContext>
      </body>
    </html>
  );
}
